version: "3.7"
services:
  samba:
    build: .
    container_name: samba
    volumes:
      - ./config/smb.conf:/etc/samba/smb.conf
      - ./business:/business
      - ./public:./public
      - ./private:/praivate
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tty: yes
    restart: always
