version: "3.7"
services:
  samba:
    build: .
    container_name: samba
    volumes:
      - ./storage/business:/mnt/business
      - ./storage/public:/mnt/public
      - ./storage/private:/mnt/private
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tty: yes
    restart: always
